server:
  port: 8080

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-sample
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/order?serverTimeZone=UTC&CharacterEncoding=UTF-8
    username: root
    password: 1234
  security:
    user:
      name: yongjun
      password: 1234

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace #쿼리 ?값 확인



