server:
    port: 8080

springdoc:
    swagger-ui:
        tags-sorter: alpha
        disable-swagger-default-url: true
        operations-sorter: method
        #doc-expansion: none //접기 여부

spring:
    #config:
        #activate:
            #on-profile: local

    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/

    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: group-sample
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

    datasource:

        #driver-class-name: com.mysql.cj.jdbc.Driver
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3306/order?serverTimeZone=UTC&CharacterEncoding=UTF-8
        username: root
        password: 1234

    security:
        user:
            name: yongjun
            password: 1234
    jpa:
        #database-platform: org.hibernate.dialect.MySQLDialect
        database-platform: org.hibernate.dialect.MariaDBDialect

        properties:
            org.hibernate:
                format_sql: true
                ddl-auto: update
                naming:
                    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                dialect: org.hibernate.dialect.MariaDBDialect
        generate-ddl: false
        open-in-view: false
        show-sql: true

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace #쿼리 ?값 확인



